#!/bin/bash

echo "========================================="
echo "Script de configuration pour Render.com"
echo "========================================="
echo ""

# Vérifier si git est initialisé
if [ ! -d ".git" ]; then
    echo "Initialisation du dépôt Git..."
    git init
    git add .
    git commit -m "Initial commit - TFJ Automation avec configuration Render"
else
    echo "Dépôt Git déjà initialisé."
fi

echo ""
echo "========================================="
echo "Étapes à suivre manuellement:"
echo "========================================="
echo ""
echo "1. Créez un repository sur GitHub:"
echo "   - Allez sur https://github.com/new"
echo "   - Nom: tfj-automation"
echo "   - Visibilité: Privé ou Public selon vos besoins"
echo ""
echo "2. Push le code vers GitHub:"
echo "   git remote add origin https://github.com/VOTRE_USERNAME/tfj-automation.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. Sur Render.com:"
echo "   a) Connectez-vous à https://dashboard.render.com/"
echo "   b) Créez une base de données PostgreSQL:"
echo "      - New → PostgreSQL"
echo "      - Name: tfj-db"
echo "      - Database: tfj_db"
echo "      - Sauvegardez les identifiants"
echo ""
echo "   c) Créez un Web Service:"
echo "      - New → Web Service"
echo "      - Connectez votre repo GitHub"
echo "      - Build Command: cd backend && mvn clean package -DskipTests"
echo "      - Start Command: java -jar backend/target/tfj-automation-1.0.0.jar --spring.profiles.active=render"
echo ""
echo "4. Variables d'environnement à configurer sur Render:"
echo "   DATABASE_URL=jdbc:postgresql://<host>:<port>/tfj_db"
echo "   DATABASE_USER=<user>"
echo "   DATABASE_PASSWORD=<password>"
echo "   JWT_SECRET=<une-cle-secrete-tres-longue>"
echo "   PORT=8080"
echo "   SPRING_PROFILES_ACTIVE=render"
echo ""
echo "5. Après déploiement, testez l'API:"
echo "   curl https://tfj-automation.onrender.com/api/actuator/health"
echo ""
echo "========================================="
echo "Pour plus de détails, consultez:"
echo "DEPLOYMENT_RENDER.md"
echo "========================================="
